### PR TITLE
postgresql expects integer for lock_timeout

### PR DESCRIPTION
**Pull request by bernardotorres**

### CODE REVIEW

**Comment by bernardotorres** [comment]
Tested this live and with this patch, it works.

**Comment by bernardotorres** [comment]
Tests passed, but getting some errors related to Coveralls

```
Trying submitting coverage with service_name: github...
cd .
Failed submitting coverage with service_name: github
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 259, in submit_report
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/entrypoint.py", line 82, in run_coveralls
    result = coveralls.wear()
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 226, in wear
    return self.submit_report(json_string)
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 262, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs
cd /github/workspace
Trying submitting coverage with service_name: github-actions...
cd .
Failed submitting coverage with service_name: github-actions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 259, in submit_report
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/entrypoint.py", line 82, in run_coveralls
    result = coveralls.wear()
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 226, in wear
    return self.submit_report(json_string)
  File "/usr/local/lib/python3.9/site-packages/coveralls/api.py", line 262, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 405 Client Error: Not Allowed for url: https://coveralls.io/api/v1/jobs
cd /github/workspace
Failed to submit coverage
ExitCode.FAILURE
```

**Comment by johnbywater** [comment]
I was going to ask you to check this one too, but didn't want to trouble you. So thank you very much for taking the initiative!

Yes, coveralls's API has been a bit less than completely reliable in recent times. Re-running all the jobs normally helps...

**Comment by bernardotorres** [comment]
Maybe I didn't look properly, but it seems i don't have permission to re-run the tests.

**Comment by johnbywater** [comment]
I reran them twice and got the same error twice, which is unusual. I think we are using the latest version of their tool so I don't know what else to do. Somebody keeps breaking their API and I don't understand it. It used to always just work. Maybe it will work tomorrow?

**Comment by johnbywater** [comment]
If you click through to the "details" there is a button top right. 
Screenshot_20210918_235600

**Comment by johnbywater** [comment]
Still not working today 😬

**Comment by bernardotorres** [comment]
That's probably only visible to repo maintainers.
image

**Comment by Unknown22** [comment]
The same problem is for idle_in_transaction_session_timeout in the same class

**Comment by johnbywater** [comment]
Looks like coveralls fixed their stuff 👍

**Pull request merged**
