### PR TITLE
separate entity version to a separate column and add unique constrain

### PR DESCRIPTION
**Pull request by renou**

### CODE REVIEW

**Comment by renou** [comment]
sorry, created by accident

**Comment by johnbywater** [comment]
That's alright. I think you've got a good idea, and I think the timestamp ID and the version number are perhaps alternative ways of constructing the sequence. I'm still not sure which is best. I would kinda prefer to use the version numbers because they create a logical sequence in themselves. And making sure the event stream doesn't become inconsistent, by using with a version number constraint in the database, does make sense. The only trouble is that technique isn't really possible in a database such as Cassandra. At the same time, perhaps if a distributed application needs to be such that an entity could become inconsistent, the it would be possible to deal with the inconsistency within the entity effectively by merging the branched sequence of events. On the other hand, although the timestamps depend on the system clock, they allow events to be created in an entity that has an ID but doesn't have version numbers, such as a message logged events in an indefinitely long log of messages. Events from versioned entities also happen at a particular time, and we're interested in that too. Since some domain events don't have a meaningful (or unique) entity version number, whilst all events do have a timestamp, the common format and mechanism for storing all domain events can't really make the entity version figure too strongly, but it can depend on there being a timestamp. I think that's why it has ended up working the way it does. It would be nice to make it support using version numbers to generate the sequence, and if you want to do that, I would suggest going a bit further up the stack, add something to the stored event, and the functions that do stuff with stored events, so you don't have to deserialise the stored event to get the entity version. If you aren't using Cassandra, then you don't need to worry about breaking that bit of the code. Anyway, it's great to see you are having fun with it :-)

**Comment by renou** [comment]
Thank you John! 👍 I will keep your advice in mind. :)

**Comment by johnbywater** [comment]
By the way, I realised recently I was wrong when I said, "The only trouble is that technique isn't really possible in a database such as Cassandra." I learned how to use the "if not exists" feature and was thinking to maybe create an alternative implementations of the stored event repositories that have a schema that uses the version ID.

**Comment by renou** [comment]
nice!

**Pull request closed without merging**
