### PR TITLE
Bump Requests Dependency Version to <= 2.25.99999

### PR DESCRIPTION
**Pull request by bartboy011**
The Requests library has rolled out a few releases that are compatible with eventsourcing, so this PR simply brings the allowed versions of Requests up to date. One thing to note - version 2.25.x will be the last minor version to support Python 3.5, but this library requires 3.6 or greater anyway, so there's no issue there.

### CODE REVIEW

**Comment by bartboy011** [comment]
Added context behind the "why" of this PR - I am working on integrating eventsourcing with [FastAPI](https://fastapi.tiangolo.com/) which currently have incompatible version requirements for Requests. This PR will reconcile those differences and allow eventsourcing and FastAPI to be used in tandem to create an async, event-sourced HTTP API microservice.

**Comment by johnbywater** [comment]
Thanks a lot @bartboy011! I will release this change as v8.2.5 tomorrow.

**Comment by bartboy011** [comment]
@johnbywater of course! Thank you for getting this out so quickly, much appreciated!

**Comment by johnbywater** [comment]
Just released to PyPI @bartboy011. I also updated the versions of the other dependencies.

https://eventsourcing.readthedocs.io/en/stable/topics/release_notes.html#version-8-2-5-released-22-dec-2020

**Pull request merged**
