### PR TITLE
Updated dockerization for local development

### PR DESCRIPTION
**Pull request by Skyross**
Hi, @johnbywater!

Here is the second MR about the dockerization for local development as we considered at [this message](https://eventsourcinginpython.slack.com/archives/C627DFVJM/p1587146929060800?thread_ts=1587139824.060200&cid=C627DFVJM):

> Docker files (so people can run all the tests without having to figure out how to set everything up)

So I assume the Contributor is able to set up his local python development environment setup packages. The main idea is about having full-featured local set up for package development and run everything else (database backends) as containers. The tests are executed from the local environment too. 

The main development flow (it should work for macOS and Linux):
- pull the repo
- `make install`
- `make docker-up`
- `make test`

What I found:
- Not all tests doing teardown in the right way: sometimes my tests failed because of the data left at DBs, so it requires `make docker-down`
- Looks like you wanted to run tests within container built with Dockerfile. Is it the main requirement for dockerization or current solution is OK?
- Some packages not in the testing package requirements (is there any reason for it?):
    - mysql-connector-python-rf
    - python-coveralls
    - "coverage<5.0.0"

Open to hear your feedback!

Best!

### CODE REVIEW

**Comment by johnbywater** [comment]
Hey @Skyross!

This is looks really great! Thanks so much.

> Not all tests doing teardown in the right way: sometimes my tests failed because of the data left at DBs

I don't doubt what you say, but I wasn't aware of this, the only trouble I've had is after sleep/resume if Axon server hasn't been stopped, then it sometimes doesn't return everything that seems to be expected.

> Looks like you wanted to run tests within container built with Dockerfile. Is it the main requirement for dockerization or current solution is OK?

There isn't really a requirement for the tests to run in Docker, or otherwise. I haven't run the tests in Dockerfile for a while, and the way I've been working doesn't depend on this, so I don't feel strongly about it. I think I was perhaps just seeing what PyCharm could do, and trying to move towards the situation you have provided for. So I'm happy to follow what you think is best.

> Some packages not in the testing package requirements (is there any reason for it?)

I don't think there is a good reason for this. So adding them, if they are missing, makes good sense to me.

Just one thing: doesn't need to be part of this PR, if it's not already there, do you think it would be worth adding some documentation somewhere, to describe the development flow? Maybe the README file unless there is a better place?

**Comment by Skyross** [comment]
@johnbywater 

> Just one thing: doesn't need to be part of this PR, if it's not already there, do you think it would be worth adding some documentation somewhere, to describe the development flow? Maybe the README file unless there is a better place?

What about the `contributing.rst`? Is it the right place for it?

**Comment by Skyross** [comment]
@johnbywater, I've just updated the code with testing packages and documentation.

**Comment by johnbywater** [comment]
> @johnbywater, I've just updated the code with testing packages and documentation.

Nice work!

**Pull request merged**
