### PR TITLE
Decouple transcoder from event store

### PR DESCRIPTION
**Pull request by johnbywater**

### CODE REVIEW

**Comment by renou** [comment]
very nice refactor, make a lot things possible 👍

**Comment by johnbywater** [comment]
thanks Bo! do you think it would be better to remove the various transcoder args from the application constructor signature, and instead of them just have a single 'transcoder' arg?

**Comment by renou** [comment]
I think so. Args like "json_encoder_cls" should not be cared other than Transcoder itself. 

On another note, currently Transcoder calls an outside serialize_domain_event function. I think serialize_domain_event function should be merged into Transcoder and get args like "json_encoder_cls" from Transcoder object property.

**Comment by renou** [comment]
The other thing bothers me is many of the methods on AbstractEventStore depends on stored_entity_id whose format is an implementation detail("EntityName::id-string-123"). I think AbstractEventStore should use more agnostic args. My proposal would be to change stored_entity_id to 2 arges: EntityClass, EntityID.

**Comment by johnbywater** [comment]
I agree. I like your proposal. In future, I'd really like to get rid of the "id_prefix" thing, so that there isn't such a thing as a "stored entity ID" that's different from the "entity ID". I was thinking the whole "id_prefix" thing really was a mistake that supports developers who don't understand what a context map is for. It's also useful for a couple of other things that could be done in better ways. So I'd like to get rid of it altogether because it adds quite a lot of complications. However, the simple thing is that the event store _only_ deals with stored entity IDs: all its methods have that argument. I guess it's a bit confusing that the event store converts domain events into stored events, whilst it is given stored entity IDs - don't be confused, they aren't the same thing.

In the current implementation, although the entity IDs are often UUIDs, they entity IDs are only required to be unique within their class, rather than universally unique. So that when they are used in a general namespace, they must be prefixed by something that distinguishes them by their class. I called the prefixed ID "stored_entity_id", but I guess it could be better named as "type_prefixed_entity_id" or "globally_unique_entity_id". I'm sure there's a better name. I suppose this came up when putting everything in the stored event table, and that's how it got its name.

**Comment by johnbywater** [comment]
I'll finish off the refactoring by doing the two things you suggested with 'json_encoder_cls' and the 'serialize_domain_event' function. Thanks for your suggestions!

**Comment by renou** [comment]
Thank you for your awesome work! :)

**Pull request merged**
